spring:
  application:
    name: risk-score-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8180/realms/ecom-realm/protocol/openid-connect/certs
